require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'app/controllers/concerns/**/*'
    - 'bin/bundle'
    - 'config/initializers/devise.rb'
RSpec/MultipleExpectations:
  Max: 2
